# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 14:15
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2017, 3, 24, 15, 15, 18, 724235), verbose_name='Created Time')),
                ('device_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Device ID')),
                ('error', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Error')),
            ],
            options={
                'verbose_name': 'Crash',
                'verbose_name_plural': 'Crashes',
                'db_table': 'crash',
            },
        ),
    ]
