# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crash',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
    ]
